// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.2
// source: storyboard.proto

package modelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoryboardService_CreateStoryboardTask_FullMethodName = "/storyboard.v1.StoryboardService/CreateStoryboardTask"
	StoryboardService_RegenerateShot_FullMethodName       = "/storyboard.v1.StoryboardService/RegenerateShot"
	StoryboardService_RenderVideo_FullMethodName          = "/storyboard.v1.StoryboardService/RenderVideo"
)

// StoryboardServiceClient is the client API for StoryboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoryboardServiceClient interface {
	CreateStoryboardTask(ctx context.Context, in *CreateStoryboardTaskRequest, opts ...grpc.CallOption) (*StoryboardReply, error)
	RegenerateShot(ctx context.Context, in *RegenerateShotRequest, opts ...grpc.CallOption) (*RegenerateShotReply, error)
	RenderVideo(ctx context.Context, in *RenderVideoRequest, opts ...grpc.CallOption) (*RenderVideoReply, error)
}

type storyboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoryboardServiceClient(cc grpc.ClientConnInterface) StoryboardServiceClient {
	return &storyboardServiceClient{cc}
}

func (c *storyboardServiceClient) CreateStoryboardTask(ctx context.Context, in *CreateStoryboardTaskRequest, opts ...grpc.CallOption) (*StoryboardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoryboardReply)
	err := c.cc.Invoke(ctx, StoryboardService_CreateStoryboardTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyboardServiceClient) RegenerateShot(ctx context.Context, in *RegenerateShotRequest, opts ...grpc.CallOption) (*RegenerateShotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateShotReply)
	err := c.cc.Invoke(ctx, StoryboardService_RegenerateShot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyboardServiceClient) RenderVideo(ctx context.Context, in *RenderVideoRequest, opts ...grpc.CallOption) (*RenderVideoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderVideoReply)
	err := c.cc.Invoke(ctx, StoryboardService_RenderVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoryboardServiceServer is the server API for StoryboardService service.
// All implementations must embed UnimplementedStoryboardServiceServer
// for forward compatibility.
type StoryboardServiceServer interface {
	CreateStoryboardTask(context.Context, *CreateStoryboardTaskRequest) (*StoryboardReply, error)
	RegenerateShot(context.Context, *RegenerateShotRequest) (*RegenerateShotReply, error)
	RenderVideo(context.Context, *RenderVideoRequest) (*RenderVideoReply, error)
	mustEmbedUnimplementedStoryboardServiceServer()
}

// UnimplementedStoryboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoryboardServiceServer struct{}

func (UnimplementedStoryboardServiceServer) CreateStoryboardTask(context.Context, *CreateStoryboardTaskRequest) (*StoryboardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStoryboardTask not implemented")
}
func (UnimplementedStoryboardServiceServer) RegenerateShot(context.Context, *RegenerateShotRequest) (*RegenerateShotReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RegenerateShot not implemented")
}
func (UnimplementedStoryboardServiceServer) RenderVideo(context.Context, *RenderVideoRequest) (*RenderVideoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderVideo not implemented")
}
func (UnimplementedStoryboardServiceServer) mustEmbedUnimplementedStoryboardServiceServer() {}
func (UnimplementedStoryboardServiceServer) testEmbeddedByValue()                           {}

// UnsafeStoryboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoryboardServiceServer will
// result in compilation errors.
type UnsafeStoryboardServiceServer interface {
	mustEmbedUnimplementedStoryboardServiceServer()
}

func RegisterStoryboardServiceServer(s grpc.ServiceRegistrar, srv StoryboardServiceServer) {
	// If the following call panics, it indicates UnimplementedStoryboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoryboardService_ServiceDesc, srv)
}

func _StoryboardService_CreateStoryboardTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoryboardTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryboardServiceServer).CreateStoryboardTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryboardService_CreateStoryboardTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryboardServiceServer).CreateStoryboardTask(ctx, req.(*CreateStoryboardTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryboardService_RegenerateShot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateShotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryboardServiceServer).RegenerateShot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryboardService_RegenerateShot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryboardServiceServer).RegenerateShot(ctx, req.(*RegenerateShotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryboardService_RenderVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryboardServiceServer).RenderVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoryboardService_RenderVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryboardServiceServer).RenderVideo(ctx, req.(*RenderVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoryboardService_ServiceDesc is the grpc.ServiceDesc for StoryboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoryboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storyboard.v1.StoryboardService",
	HandlerType: (*StoryboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStoryboardTask",
			Handler:    _StoryboardService_CreateStoryboardTask_Handler,
		},
		{
			MethodName: "RegenerateShot",
			Handler:    _StoryboardService_RegenerateShot_Handler,
		},
		{
			MethodName: "RenderVideo",
			Handler:    _StoryboardService_RenderVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storyboard.proto",
}
