// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.2
// source: storyboard.proto

package modelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShotResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShotId        string                 `protobuf:"bytes,1,opt,name=shot_id,json=shotId,proto3" json:"shot_id,omitempty"`
	Sequence      string                 `protobuf:"bytes,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Script        string                 `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	Details       string                 `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	Narration     string                 `protobuf:"bytes,7,opt,name=narration,proto3" json:"narration,omitempty"`
	Type          string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Transition    string                 `protobuf:"bytes,9,opt,name=transition,proto3" json:"transition,omitempty"`
	Voice         string                 `protobuf:"bytes,10,opt,name=voice,proto3" json:"voice,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,11,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Bgm           string                 `protobuf:"bytes,12,opt,name=bgm,proto3" json:"bgm,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,13,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShotResult) Reset() {
	*x = ShotResult{}
	mi := &file_storyboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotResult) ProtoMessage() {}

func (x *ShotResult) ProtoReflect() protoreflect.Message {
	mi := &file_storyboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotResult.ProtoReflect.Descriptor instead.
func (*ShotResult) Descriptor() ([]byte, []int) {
	return file_storyboard_proto_rawDescGZIP(), []int{0}
}

func (x *ShotResult) GetShotId() string {
	if x != nil {
		return x.ShotId
	}
	return ""
}

func (x *ShotResult) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *ShotResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShotResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShotResult) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ShotResult) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ShotResult) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

func (x *ShotResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ShotResult) GetTransition() string {
	if x != nil {
		return x.Transition
	}
	return ""
}

func (x *ShotResult) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *ShotResult) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ShotResult) GetBgm() string {
	if x != nil {
		return x.Bgm
	}
	return ""
}

func (x *ShotResult) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type CreateStoryboardTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	StoryId       string                 `protobuf:"bytes,2,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ScriptContent string                 `protobuf:"bytes,5,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"`
	Style         string                 `protobuf:"bytes,6,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoryboardTaskRequest) Reset() {
	*x = CreateStoryboardTaskRequest{}
	mi := &file_storyboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoryboardTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryboardTaskRequest) ProtoMessage() {}

func (x *CreateStoryboardTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storyboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryboardTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateStoryboardTaskRequest) Descriptor() ([]byte, []int) {
	return file_storyboard_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStoryboardTaskRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CreateStoryboardTaskRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *CreateStoryboardTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateStoryboardTaskRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateStoryboardTaskRequest) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

func (x *CreateStoryboardTaskRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

type StoryboardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shots         []*ShotResult          `protobuf:"bytes,1,rep,name=shots,proto3" json:"shots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryboardReply) Reset() {
	*x = StoryboardReply{}
	mi := &file_storyboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryboardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryboardReply) ProtoMessage() {}

func (x *StoryboardReply) ProtoReflect() protoreflect.Message {
	mi := &file_storyboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryboardReply.ProtoReflect.Descriptor instead.
func (*StoryboardReply) Descriptor() ([]byte, []int) {
	return file_storyboard_proto_rawDescGZIP(), []int{2}
}

func (x *StoryboardReply) GetShots() []*ShotResult {
	if x != nil {
		return x.Shots
	}
	return nil
}

type RegenerateShotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	StoryId       string                 `protobuf:"bytes,2,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	ShotId        string                 `protobuf:"bytes,3,opt,name=shot_id,json=shotId,proto3" json:"shot_id,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Style         string                 `protobuf:"bytes,5,opt,name=style,proto3" json:"style,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateShotRequest) Reset() {
	*x = RegenerateShotRequest{}
	mi := &file_storyboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateShotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateShotRequest) ProtoMessage() {}

func (x *RegenerateShotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storyboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateShotRequest.ProtoReflect.Descriptor instead.
func (*RegenerateShotRequest) Descriptor() ([]byte, []int) {
	return file_storyboard_proto_rawDescGZIP(), []int{3}
}

func (x *RegenerateShotRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RegenerateShotRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *RegenerateShotRequest) GetShotId() string {
	if x != nil {
		return x.ShotId
	}
	return ""
}

func (x *RegenerateShotRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *RegenerateShotRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *RegenerateShotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RegenerateShotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shot          *ShotResult            `protobuf:"bytes,1,opt,name=shot,proto3" json:"shot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateShotReply) Reset() {
	*x = RegenerateShotReply{}
	mi := &file_storyboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateShotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateShotReply) ProtoMessage() {}

func (x *RegenerateShotReply) ProtoReflect() protoreflect.Message {
	mi := &file_storyboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateShotReply.ProtoReflect.Descriptor instead.
func (*RegenerateShotReply) Descriptor() ([]byte, []int) {
	return file_storyboard_proto_rawDescGZIP(), []int{4}
}

func (x *RegenerateShotReply) GetShot() *ShotResult {
	if x != nil {
		return x.Shot
	}
	return nil
}

type RenderVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	StoryId       string                 `protobuf:"bytes,2,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderVideoRequest) Reset() {
	*x = RenderVideoRequest{}
	mi := &file_storyboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderVideoRequest) ProtoMessage() {}

func (x *RenderVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storyboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderVideoRequest.ProtoReflect.Descriptor instead.
func (*RenderVideoRequest) Descriptor() ([]byte, []int) {
	return file_storyboard_proto_rawDescGZIP(), []int{5}
}

func (x *RenderVideoRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RenderVideoRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *RenderVideoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RenderVideoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	VideoData     []byte                 `protobuf:"bytes,2,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderVideoReply) Reset() {
	*x = RenderVideoReply{}
	mi := &file_storyboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderVideoReply) ProtoMessage() {}

func (x *RenderVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_storyboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderVideoReply.ProtoReflect.Descriptor instead.
func (*RenderVideoReply) Descriptor() ([]byte, []int) {
	return file_storyboard_proto_rawDescGZIP(), []int{6}
}

func (x *RenderVideoReply) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *RenderVideoReply) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

var File_storyboard_proto protoreflect.FileDescriptor

const file_storyboard_proto_rawDesc = "" +
	"\n" +
	"\x10storyboard.proto\x12\rstoryboard.v1\"\xe1\x02\n" +
	"\n" +
	"ShotResult\x12\x17\n" +
	"\ashot_id\x18\x01 \x01(\tR\x06shotId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\tR\bsequence\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06script\x18\x05 \x01(\tR\x06script\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\x12\x1c\n" +
	"\tnarration\x18\a \x01(\tR\tnarration\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"transition\x18\t \x01(\tR\n" +
	"transition\x12\x14\n" +
	"\x05voice\x18\n" +
	" \x01(\tR\x05voice\x12\x1b\n" +
	"\timage_url\x18\v \x01(\tR\bimageUrl\x12\x10\n" +
	"\x03bgm\x18\f \x01(\tR\x03bgm\x12\x1d\n" +
	"\n" +
	"image_data\x18\r \x01(\fR\timageData\"\xd4\x01\n" +
	"\x1bCreateStoryboardTaskRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x19\n" +
	"\bstory_id\x18\x02 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12%\n" +
	"\x0escript_content\x18\x05 \x01(\tR\rscriptContent\x12\x14\n" +
	"\x05style\x18\x06 \x01(\tR\x05style\"B\n" +
	"\x0fStoryboardReply\x12/\n" +
	"\x05shots\x18\x01 \x03(\v2\x19.storyboard.v1.ShotResultR\x05shots\"\xb7\x01\n" +
	"\x15RegenerateShotRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x19\n" +
	"\bstory_id\x18\x02 \x01(\tR\astoryId\x12\x17\n" +
	"\ashot_id\x18\x03 \x01(\tR\x06shotId\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x12\x14\n" +
	"\x05style\x18\x05 \x01(\tR\x05style\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"D\n" +
	"\x13RegenerateShotReply\x12-\n" +
	"\x04shot\x18\x01 \x01(\v2\x19.storyboard.v1.ShotResultR\x04shot\"k\n" +
	"\x12RenderVideoRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x19\n" +
	"\bstory_id\x18\x02 \x01(\tR\astoryId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"N\n" +
	"\x10RenderVideoReply\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\x12\x1d\n" +
	"\n" +
	"video_data\x18\x02 \x01(\fR\tvideoData2\xa6\x02\n" +
	"\x11StoryboardService\x12b\n" +
	"\x14CreateStoryboardTask\x12*.storyboard.v1.CreateStoryboardTaskRequest\x1a\x1e.storyboard.v1.StoryboardReply\x12Z\n" +
	"\x0eRegenerateShot\x12$.storyboard.v1.RegenerateShotRequest\x1a\".storyboard.v1.RegenerateShotReply\x12Q\n" +
	"\vRenderVideo\x12!.storyboard.v1.RenderVideoRequest\x1a\x1f.storyboard.v1.RenderVideoReplyB2Z0story2video-backend/internal/rpc/modelpb;modelpbb\x06proto3"

var (
	file_storyboard_proto_rawDescOnce sync.Once
	file_storyboard_proto_rawDescData []byte
)

func file_storyboard_proto_rawDescGZIP() []byte {
	file_storyboard_proto_rawDescOnce.Do(func() {
		file_storyboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storyboard_proto_rawDesc), len(file_storyboard_proto_rawDesc)))
	})
	return file_storyboard_proto_rawDescData
}

var file_storyboard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_storyboard_proto_goTypes = []any{
	(*ShotResult)(nil),                  // 0: storyboard.v1.ShotResult
	(*CreateStoryboardTaskRequest)(nil), // 1: storyboard.v1.CreateStoryboardTaskRequest
	(*StoryboardReply)(nil),             // 2: storyboard.v1.StoryboardReply
	(*RegenerateShotRequest)(nil),       // 3: storyboard.v1.RegenerateShotRequest
	(*RegenerateShotReply)(nil),         // 4: storyboard.v1.RegenerateShotReply
	(*RenderVideoRequest)(nil),          // 5: storyboard.v1.RenderVideoRequest
	(*RenderVideoReply)(nil),            // 6: storyboard.v1.RenderVideoReply
}
var file_storyboard_proto_depIdxs = []int32{
	0, // 0: storyboard.v1.StoryboardReply.shots:type_name -> storyboard.v1.ShotResult
	0, // 1: storyboard.v1.RegenerateShotReply.shot:type_name -> storyboard.v1.ShotResult
	1, // 2: storyboard.v1.StoryboardService.CreateStoryboardTask:input_type -> storyboard.v1.CreateStoryboardTaskRequest
	3, // 3: storyboard.v1.StoryboardService.RegenerateShot:input_type -> storyboard.v1.RegenerateShotRequest
	5, // 4: storyboard.v1.StoryboardService.RenderVideo:input_type -> storyboard.v1.RenderVideoRequest
	2, // 5: storyboard.v1.StoryboardService.CreateStoryboardTask:output_type -> storyboard.v1.StoryboardReply
	4, // 6: storyboard.v1.StoryboardService.RegenerateShot:output_type -> storyboard.v1.RegenerateShotReply
	6, // 7: storyboard.v1.StoryboardService.RenderVideo:output_type -> storyboard.v1.RenderVideoReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storyboard_proto_init() }
func file_storyboard_proto_init() {
	if File_storyboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storyboard_proto_rawDesc), len(file_storyboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storyboard_proto_goTypes,
		DependencyIndexes: file_storyboard_proto_depIdxs,
		MessageInfos:      file_storyboard_proto_msgTypes,
	}.Build()
	File_storyboard_proto = out.File
	file_storyboard_proto_goTypes = nil
	file_storyboard_proto_depIdxs = nil
}
